### PR TITLE
Works with H100 (AU) HW: 2.0, SW:1.0.10 now

### PR DESCRIPTION
**Pull request by uwwint**
Works with H100 (AU) HW: 2.0, SW:1.0.10 now.

Unfortunately cannot test compatibility with other versions.

### CODE REVIEW

**Comment by uwwint** [comment]
Confirmed change working with other hardware versions as well. See: 
https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/issues/3

this fixes 
https://github.com/softScheck/tplink-smartplug/issues/22

**Comment by rct** [comment]
Posted this in #22, but probably should have been here.

I have a couple of HS100/HS110 (US) modules. The code with and without the above patch to encrypt seems to work fine with those modules.  So I think it's worth merging this PR.

However I have a new mini plug HS105 (US), HW version 1.0, firmware version 1.2.9 that doesn't seem to respond with or without this patch. The thread at [jneilliii/OctoPrint-TPLinkSmartplug#3](https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/issues/3) seems to indicate the HS105 works with the updated encrypt function.   I don't know if I'm just missing something or there is some other difference for this.

I'll probably open up a separate issue for the HS105.

**Comment by xaviervilla** [comment]
Confirmed still working on HS100 (US). [with and without this patch]

**Comment by softScheck** [comment]
Already solved.

**Pull request closed without merging**
